apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: tundedamian/flask-observability:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: JAEGER_AGENT_HOST
          value: "jaeger"
        - name: JAEGER_AGENT_PORT
          value: "4317"
        - name: PROMETHEUS_MULTIPROC_DIR
          value: "/tmp"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

