name: Build & Push Flask Observability Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  DOCKERHUB_USERNAME: tundedamian
  DOCKERHUB_REPO: flask-observability

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Extract Git info
        id: git-info
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          IMAGE_TAG=${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${BRANCH_NAME}-${COMMIT_SHA}
          docker build -t $IMAGE_TAG ./flask-app
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image
        run: docker push $IMAGE_TAG
